In [1]:
#install gym package
!pip install --upgrade gym==0.23.0

import numpy as np
import gym # pip intall gym
import random
env = gym.make('FrozenLake-v1', is_slippery = False)

action_space_size = env.action_space.n
state_space_size = env.observation_space.n

qtable = np.zeros((state_space_size, action_space_size))
qtable

#Hyper Parameters

total_episodes = 10000
learning_rate = 0.2 # 0-1
max_steps = 100
gamma = 0.99

epsilon = 1
max_epsilon = 1
min_epsilon = 0.01
decay_rate = 0.001

rewards = []

for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        if random.uniform(0,1) > epsilon:
            action = np.argmax(qtable[state,:]) #Exploit
        else:
            action = env.action_space.sample() #Explore
            
        new_state, reward, done, info = env.step(action)
        
        max_new_state = np.max(qtable[new_state,:])
        
        qtable[state,action] = qtable[state,action] + learning_rate*(reward+gamma*max_new_state-qtable[state,action])
        
        total_rewards += reward
        
        state = new_state
        if done:
            break
        
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)
        
print("Score:", str(sum(rewards)/total_episodes))



print(qtable)


qtable[state,action] = qtable[state,action] + learning_rate*(reward+gamma*max_new_state-qtable[state,action])

env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    
    print("Episode:", episode+1)
    
    for step in range(max_steps):
        action = np.argmax(qtable[state,:])
        new_state, reward, done, info = env.step(action)
        env.render()
        if done:
            
            print("Number of Steps:", step)
            break
        state = new_state
        
env.close()

Score: 0.8759
[[0.94148015 0.93206535 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.95014224 0.95043644]
 [0.93146969 0.91143499 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.74976301 0.         0.68433058 0.93113775]
 [0.83287726 0.96816619 0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.94396565 0.99       0.91987766]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]
Episode: 1
Number of Steps: 5
Episode: 2
Number of Steps: 5
Episode: 3
Number of Steps: 5
Episode: 4
Number of Steps: 5
Episode: 5
Number of Steps: 5
